application:
    name: sedex-kingfisher-api-gateway
    
spring
	profiles=default
	
security
	basic
		enabled=false

db
	url=jdbc:postgresql://10.0.40.12:5432/sedex_data_pipeline_v2_staging
	driverClass=org.postgresql.Driver
	username=kingfisher_api
	password=5Q81q1qHXNHiGj5M

kingfisher
	code
		zc=ZC3252996
		zu=ZU3252997

---
spring
	profiles=dev

security
	basic
		enabled=false

db
	url=jdbc:postgresql://10.0.40.12:5432/sedex_data_pipeline_v2_staging
	driverClass=org.postgresql.Driver
	username=kingfisher_api
	password=5Q81q1qHXNHiGj5M

kingfisher
	code
		zc=ZC1055758
		zu=ZU1013766

---
spring
	profiles=prod

security
	basic
		enabled=false

db
	url=jdbc:postgresql://10.0.40.12:5432/sedex_data_pipeline_v2_staging
	driverClass=org.postgresql.Driver
	username=kingfisher_api
	password=5Q81q1qHXNHiGj5M

kingfisher
	code
		zc=ZC3252996
		zu=ZU3252997

logging:
	config: http://artefacts.internal.sedexonline.com/logconfig/sedex-kingfisher-api-gateway-prod.xml		
---

spring
	profiles=qa
	
security
	basic
		enabled=false
		
db
	url=jdbc:postgresql://10.0.40.10:5432/sedex_data_pipeline_v2_qa
	driverClass=org.postgresql.Driver
	username=kingfisher_api
	password=kingfisher_api

kingfisher
	code
		zc=ZC3252996
		zu=ZU3252997

logging:
	config: http://artefacts.internal.sedexonline.com/logconfig/sedex-kingfisher-api-gateway-qa.xml
---

spring
	profiles=staging
	
security
	basic
		enabled=false

db
	url=jdbc:postgresql://10.0.40.12:5432/sedex_data_pipeline_v2_staging
	driverClass=org.postgresql.Driver
	username=kingfisher_api
	password=5Q81q1qHXNHiGj5M

kingfisher
	code
		zc=ZC1055758
		zu=ZU1013766
logging:
	config: http://artefacts.internal.sedexonline.com/logconfig/sedex-kingfisher-api-gateway-staging.xml		
